apiVersion: apps/v1
kind: Deployment
metadata:
  name: juiceshop
  labels:
    apps: juiceshop
spec:
  replicas: 3
  selector:
    matchLabels:
      app: juiceshop
  template:
    metadata:
      labels:
        app: juiceshop
    spec:
      containers:
        - name: juiceshop
          image: bkimminich/juice-shop
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: juiceshop-service
spec:
  selector:
    app: juiceshop
  ports:
    - protocol: TCP
      port: 3000
